name: mdict release
on: 
  push:
    branches:
    - main
jobs:
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: marvipinto/action-automatic-releases@latest
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          prerelease: false