name: mdict CLI CI/CD

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'
      - run: pip3 install .
      - run: python3 -m unittest discover -s tests -p "*test.py"
      